name: Slack Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read version file
        id: read_version
        run: |
          echo "VERSION_CONTENT=$(cat version.txt)" >> $GITHUB_ENV

      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "mrkdwn",
                    "text": "New version is released for ${{github.repository}}!"
                  }
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": " > Version: 1.1.1."
                    }
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": " > Version: 1.1.1."
                    }
                },
                {
                    "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "```
                    Release Notes:
                    ${{ env.VERSION_CONTENT }}
                    ```"
                  }
                }
              ]
            }
